name: Android Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  android-unit-test:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: dependencies
        run: |
          npm install
          cd example
          npm pack ..
          npm install
          cd ..

      - name: test
        run: |
          cd android
          ./gradlew test
          cd ..

      - name: example-test
        run: |
          cd example/android
          ./gradlew test
          cd ../..

      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: ${{ github.workspace }}/*/build/reports/
