name: Release

on:
  release:
    types: [published]

jobs:
  finalize_release:
    name: Finalize Release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: "master"
          token: ${{secrets.SERVICE_PERSONAL_ACCESS_TOKEN}}

      - name: get current tag
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: update version
        env:
          TAG_VERSION: ${{ steps.get_tag.outputs.VERSION }}
        run: |
          sed -i -E 's/^  "version": "[^"]+",$/  "version": "'"$TAG_VERSION"'",/g' package.json
          cat package.json
          sed -i -E 's/^    "react-native-cardverify": "[^"]+",$/    "react-native-cardverify": "file:react-native-cardverify-'"$TAG_VERSION"'.tgz",/g' example/package.json
          cat example/package.json

      - name: update package lock
        run: |
          npm install

      - name: update example package lock
        run: |
          cd example
          npm pack ..
          npm update
          npm install
          cd ..

      - name: generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          user: "getbouncer"
          project: "react-native-cardverify"
          repo: "getbouncer/react-native-cardverify"
          token: ${{ secrets.SERVICE_PERSONAL_ACCESS_TOKEN }}
          pullRequests: "true"
          prWoLabels: "true"
          issues: "true"
          issuesWoLabels: "true"
          author: "true"
          base: "HISTORY.md"
          unreleased: "true"
          breakingLabels: "Versioning - BREAKING"
          enhancementLabels: "Type - Enhancement, Type - Feature"
          bugLabels: "Type - Fix, Bug - Fixed"
          deprecatedLabels: "Type - Deprecated"
          removedLabels: "Type - Removal"
          securityLabels: "Security Fix"
          excludeLabels: "Skip-Changelog"

      - name: create commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic changelog update"
          file_pattern: "package.json package-lock.json example/package.json example/package-lock.json CHANGELOG.md"

  publish-npm:
    needs: finalize_release
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: "master"

      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: prepublish
        run: |
          npm install

      - name: publish to NPM
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
